# -*- coding: utf-8 -*-
"""POAD_TP2_GPS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10DCM5MpyFC10FNiu88YsduUlvbqlJro2

# IES 9008: **POAD**
## Trabajo Práctico n°2
### _Estudiante: Sol Gantuz Ponce_
"""

import pandas as pd
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("POAD-TP2-ETL").getOrCreate()

"""## Importe 2 o más fuentes sobre una misma temática, organice y concatena en al menos 1 DataFrame.

Las fuentes de los Datasets son:
- https://www.kaggle.com/datasets/sahilislam007/ai-impact-on-job-market-20242030?resource=download
- https://www.kaggle.com/datasets/sumeakash/ai-impact-on-job-sector

### ETL
"""

# 1) Leer los csv con pandas
pdf_1 = pd.read_csv("ai_job_trends_dataset.csv")

pdf_2 = pd.read_csv("ai_job_impact.csv")

# 2) Convertir a DataFrame de Spark
df_1 = spark.createDataFrame(pdf_1)

df_2 = spark.createDataFrame(pdf_2)

# 3.1) Revisar estructura
df_1.printSchema()
df_1.show(5)

# 3.1) Revisar estructura
print("Filas:", df_1.count())
print("Columnas:", len(df_1.columns))
df_1.describe(["Industry", "Required Education"]).show()

# 3.3.1) Revisar valores únicos de las columnas
df_1.select("Industry").distinct().show()

# 3.3.1) Revisar valores únicos de las columnas
df_1.select("Required Education").distinct().show()

# 3.2) Revisar estructura
df_2.printSchema()
df_2.show(5)

# 3.2) Revisar estructura
print("Filas:", df_2.count())
print("Columnas:", len(df_2.columns))
df_2.describe(["Industry", "Education_Level"]).show()

# 3.3.2) Revisar valores únicos de las columnas
df_2.select("Industry").distinct().show()

# 3.3.2) Revisar valores únicos de las columnas
df_2.select("Education_Level").distinct().show()

# 4.1) Hacer copias de los DF para manipular con tranquilidad
df_copia_1 = df_1.select('*')

# 4.2) Hacer copias de los DF para manipular con tranquilidad
df_copia_2 = df_2.select('*')

# from pyspark.sql import functions as F

# df_copia.agg(*[F.sum(F.when(F.col(c).isNull(), 1).otherwise(0)).alias(c) for c in df_copia.columns]).show()

from pyspark.sql import functions as F

# Revisar el top 10 de trabajo remoto en el dataset 1 original
print("--- TOP 10 TRABAJO REMOTO EN DF1 ORIGINAL ---")
display(
    df_copia_1.groupBy('Job Title')\
    .agg(F.mean('Remote Work Ratio (%)').alias('Remote Work Ratio (%)'))\
    .orderBy(F.col('Remote Work Ratio (%)').desc())\
    .limit(10)
    .toPandas()
)

# Revisar si hay duplicados o cuántas filas existen por puesto en DF1
print("\n--- REGISTROS POR PUESTO EN DF1 ORIGINAL (Muestra) ---")
display(
    df_copia_1.groupBy('Job Title').count()\
    .orderBy(F.col('count').desc())\
    .limit(10)
    .toPandas()
)

from pyspark.sql import functions as F

# 1. TRANSFORMACIÓN Y HOMOLOGACIÓN DE DF_1 (JOB MARKET)
df_1_transformed = df_copia_1 \
    .withColumn("Industry", F.trim(F.col("Industry"))) \
    .withColumn("Job_Title", F.trim(F.col("Job Title"))) \
    .withColumn("Market_Required_Education",
        F.when(F.col("Required Education").contains("Master"), "Master")
         .when(F.col("Required Education").contains("Bachelor"), "Bachelor")
         .when(F.col("Required Education").contains("PhD"), "PhD")
         .when(F.col("Required Education").contains("High School"), "High School")
         .otherwise(F.trim(F.col("Required Education")))
    ) \
    .withColumn("Market_Automation_Risk_Cat",
        F.when(F.col("Automation Risk (%)") < 33.0, "Low")
         .when(F.col("Automation Risk (%)") < 66.0, "Moderate")
         .otherwise("High")
    ) \
    .select(
        F.col("Industry"),
        F.col("Job_Title"),
        F.col("Job Status").alias("Market_Job_Status"),
        F.col("AI Impact Level").alias("Market_AI_Impact_Level"),
        F.col("Median Salary (USD)").cast("double").alias("Market_Median_Salary_USD"),
        F.col("Market_Required_Education"),
        F.col("Experience Required (Years)").cast("double").alias("Market_Experience_Required_Yrs"),
        F.col("Job Openings (2024)").cast("integer").alias("Market_Job_Openings_2024"),
        F.col("Projected Openings (2030)").cast("integer").alias("Market_Projected_Openings_2030"),
        F.col("Remote Work Ratio (%)").cast("double").alias("Market_Remote_Work_Ratio_Pct"),
        F.col("Automation Risk (%)").cast("double").alias("Market_Automation_Risk_Pct"),
        F.col("Market_Automation_Risk_Cat"),
        F.col("Location")
    )

# 2. TRANSFORMACIÓN Y AGRUPACIÓN DE DF_2 (EMPLOYEES SAMPLE)

# A. Limpieza de cadenas e indicador de trabajo remoto
df_2_transformed = df_copia_2 \
    .withColumn("Industry", F.trim(F.col("Industry"))) \
    .withColumn("Job_Role", F.trim(F.col("Job_Role"))) \
    .withColumn("is_remote", F.when(F.trim(F.col("Remote_Work")) == "Yes", 1.0).otherwise(0.0))

# B. Agregación a nivel de Industria y Rol
df_2_agg = df_2_transformed.groupBy("Industry", "Job_Role").agg(
    F.count("Employee_ID").alias("Emp_Sample_Size"),
    F.percentile_approx("Salary_Before_AI", 0.5).alias("Emp_Median_Salary_Before"),
    F.percentile_approx("Salary_After_AI", 0.5).alias("Emp_Median_Salary_After"),
    (F.avg("is_remote") * 100.0).alias("Emp_Remote_Work_Ratio_Pct"),
    F.avg("Job_Satisfaction").alias("Emp_Avg_Satisfaction"),
    F.avg("Productivity_Change_%").alias("Emp_Avg_Productivity_Change_Pct"),
    F.avg("Work_Hours_Per_Week").alias("Emp_Avg_Work_Hours")
)

# 3. CONSOLIDACIÓN (LEFT JOIN)

# Unión sobre las claves compuestas: Industry y Job_Title / Job_Role
df_consolidated = df_1_transformed.join(
    df_2_agg,
    (df_1_transformed["Industry"] == df_2_agg["Industry"]) &
    (df_1_transformed["Job_Title"] == df_2_agg["Job_Role"]),
    how="left"
) \
.drop(df_2_agg["Industry"]) \
.drop(df_2_agg["Job_Role"])

# Rellenar valores nulos de las agregaciones si una combinación del mercado no tuvo encuestados
df_consolidated = df_consolidated.fillna({"Emp_Sample_Size": 0})

df_2_agg.printSchema()
df_2_agg.show(5)

df_1_transformed.printSchema()
df_1_transformed.show(5)

"""Se integraron dos orígenes de datos mediante un pipeline de ETL en PySpark. Para garantizar la consistencia analítica y evitar duplicación de observaciones por disparidad de granularidad (30.000 registros de puestos globales vs. 2.000 registros de empleados individuales), el dataset de empleados (DF2) fue sometido a una agregación previa (groupBy) a nivel de Industry y Job_Role.

Transformaciones y homologaciones clave:

1. Trabajo remoto: la variable categórica Remote_Work (Yes/No) del DF2 se transformó en una métrica porcentual continua (Emp_Remote_Work_Ratio_Pct) para permitir la comparación directa con la variable Remote Work Ratio (%) del DF1.
2. Riesgo de automatización: se derivó la columna categórica Market_Automation_Risk_Cat en el DF1 a partir de sus valores porcentuales para hacerla homologable con las escalas cualitativas del DF2.
3. Se estandarizó la columna de educación requerida en DF1 para simplificar valores extensos (de "Master’s Degree" a "Master").
4. Tipos de datos y Nulos: se castearon las métricas cuantitativas a tipos numéricos (double/integer) y se asignó un valor por defecto ($0$) al tamaño de muestra (Emp_Sample_Size) para combinaciones sin encuestados.
5. Unión: se ejecutó un LEFT JOIN conservando el 100% de la representatividad del mercado global (DF1) utilizando la clave compuesta [Industry, Job_Title] <--> [Industry, Job_Role].
"""

# 4. COMPROBACIÓN Y CONVERSIÓN A PANDAS PARA VISUALIZACIÓN

# Muestra del DataFrame final
print("Estructura final del DataFrame:")
df_consolidated.printSchema()

df_consolidated.show(5, truncate=False)

df_final_pd = df_consolidated.toPandas()
df_final_pd.head()

# Verificar tamaño del dataframe original vs final
print("Cantidad de filas en df_final_pd:", len(df_final_pd))

# Ver los valores máximos y mínimos de riesgo de automatización
print("Riesgo Mínimo:", df_final_pd['Market_Automation_Risk_Pct'].min())
print("Riesgo Máximo:", df_final_pd['Market_Automation_Risk_Pct'].max())

# Revisar el top 10 de trabajo remoto tras el merge
print("--- TOP 10 TRABAJO REMOTO EN DATAFRAME FINAL ---")
display(
    df_final_pd.groupby('Job_Title')['Market_Remote_Work_Ratio_Pct']
    .mean()
    .reset_index()
    .sort_values(by='Market_Remote_Work_Ratio_Pct', ascending=False)
    .head(10)
)

# Verificar si creció el número de filas de forma anormal
print(f"\nFilas en DF1 original: {df_copia_1.count()}")
print(f"Filas en DataFrame final consolidado: {len(df_final_pd)}")

"""## A partir del DataFrame, programe 1 gráfico o 1 widget en matplotlib."""

import matplotlib.pyplot as plt
import ipywidgets as widgets
from ipywidgets import interact

# 1. Definir las métricas disponibles para el selector
opciones_metricas = {
    'Riesgo de automatización (%)': 'Market_Automation_Risk_Pct',
    'Salario mediano (USD)': 'Market_Median_Salary_USD',
    'Porcentaje de trabajo remoto (%)': 'Market_Remote_Work_Ratio_Pct',
    'Años de experiencia requerida': 'Market_Experience_Required_Yrs'
}

# 2. Función del gráfico en Matplotlib
def graficar_top_puestos(metrica_etiqueta):
    columna_metrica = opciones_metricas[metrica_etiqueta]

    # Agrupar por puesto para calcular el promedio de la métrica seleccionada
    top_10 = (
        df_final_pd.groupby('Job_Title', as_index=False)[columna_metrica]
        .mean()
        .nlargest(10, columna_metrica)
    )

    # Crear figura y ejes
    fig, ax = plt.subplots(figsize=(9, 5))

    # Dibujar barras horizontales
    barras = ax.barh(
        top_10['Job_Title'],
        top_10[columna_metrica],
        color='#34495e',
        edgecolor='black',
        alpha=0.85
    )

    # Personalización sencilla
    ax.set_xlabel(metrica_etiqueta, fontsize=11, fontweight='bold')
    ax.set_title(f'Top 10 roles con mayor: {metrica_etiqueta}', fontsize=12, fontweight='bold', pad=12)
    ax.grid(axis='x', linestyle='--', alpha=0.5)
    ax.invert_yaxis()  # Invertir eje Y para ver el primer puesto arriba

    # Etiquetar los valores en las barras
    for barra in barras:
        ancho = barra.get_width()
        formato = f'${ancho:,.0f}' if 'USD' in metrica_etiqueta else f'{ancho:.1f}'
        ax.text(
            ancho * 1.01,
            barra.get_y() + barra.get_height()/2,
            formato,
            va='center',
            fontsize=9
        )

    plt.tight_layout()
    plt.show()

# 3. Widget interactivo
interact(
    graficar_top_puestos,
    metrica_etiqueta=widgets.Dropdown(
        options=list(opciones_metricas.keys()),
        value='Riesgo de automatización (%)',
        description='Métrica:',
        style={'description_width': 'initial'}
    )
);

import matplotlib.pyplot as plt

# Distribución del riesgo de automatización en el mercado
fig, ax = plt.subplots(figsize=(8, 4))

# Histograma en Matplotlib
n, bins, patches = ax.hist(
    df_final_pd['Market_Automation_Risk_Pct'],
    bins=15,
    color='#2c3e50',
    edgecolor='white',
    alpha=0.85
)

ax.set_title('Distribución del riesgo de automatización en el mercado laboral', fontsize=12, fontweight='bold')
ax.set_xlabel('Riesgo de automatización (%)', fontsize=10)
ax.set_ylabel('Frecuencia (cantidad de puestos)', fontsize=10)
ax.grid(axis='y', linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()

"""## También programe 1 gráfico en Seaborn."""

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")
fig, ax = plt.subplots(figsize=(9, 5))
orden_impacto = ['Low', 'Moderate', 'High']

sns.boxplot(
    data=df_final_pd,
    x='Market_AI_Impact_Level',
    y='Market_Median_Salary_USD',
    order=orden_impacto,
    palette='Blues',
    ax=ax,
    fliersize=3,
    linewidth=1.2
)

ax.set_title('Distribución salarial según el nivel de impacto de la Inteligencia Artificial', fontsize=12, fontweight='bold', pad=12)
ax.set_xlabel('Nivel de impacto de la IA', fontsize=10, fontweight='bold')
ax.set_ylabel('Salario mediano anual (USD)', fontsize=10, fontweight='bold')

# Formatear el eje Y con separadores de miles para mejor lectura
ax.yaxis.set_major_formatter('${x:,.0f}')

plt.tight_layout()
plt.show()

"""Al analizar las distribuciones mediante diagramas de caja (boxplots) e histogramas, se observa una varianza y mediana homogéneas entre categorías. Esto evidencia que el dataset de origen sigue una distribución uniforme aleatoria (datos sintéticos), por lo que las variables no presentan correlación ni sesgos del mundo real.

## Programe 1 gráfico interactivo en express o graph_objects de plotly.
"""

import plotly.express as px

df_plotly = df_final_pd.groupby(
    ['Job_Title', 'Industry', 'Market_AI_Impact_Level'],
    as_index=False
)[['Market_Automation_Risk_Pct', 'Market_Median_Salary_USD']].mean()


fig = px.scatter(
    df_plotly,
    x='Market_Automation_Risk_Pct',
    y='Market_Median_Salary_USD',
    color='Market_AI_Impact_Level',
    hover_name='Job_Title',
    hover_data=['Industry'],
    title='<b>Relación entre riesgo de automatización y la mediana del salario por rol</b>',
    labels={
        'Market_Automation_Risk_Pct': 'Riesgo de automatización (%)',
        'Market_Median_Salary_USD': 'Salario anual mediana (USD)',
        'Market_AI_Impact_Level': 'Impacto de IA'
    },
    color_discrete_sequence=px.colors.qualitative.Set1,
    opacity=0.75
)


fig.update_layout(
    template='plotly_white',
    legend_title_text='Nivel impacto IA',
    font=dict(family="Arial", size=12)
)


fig.show()

